Repository short-d/crawler, pull requests merged in 2020-08, with the labels that each got.

#3 Add Vinod to README
  README.md
Labels: size/XS

#4 Migrate master server to use app framework
  go.mod
  go.sum
  master/server.go
Labels: size/S

#5 Tools script
  scripts/tools
Labels: size/XS

#7 Refact master in worker
  worker/master_client.go
  worker/server.go
  worker/worker.go
Labels: size/M

#9 Migrate Worker to use app framework
  master/worker.go
  worker/server.go
Labels: size/M
